// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD47rd-r8JK55NEScpDZduBnD3tM0Y2GWo',
    appId: '1:573518666505:web:bbcb4be87b8ea3176bd1d8',
    messagingSenderId: '573518666505',
    projectId: 'tutorial-a8d55',
    authDomain: 'tutorial-a8d55.firebaseapp.com',
    storageBucket: 'tutorial-a8d55.appspot.com',
    measurementId: 'G-47PZDPJQBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFLhudIuchJkW95nE5ObeRDdJlrG4T4gg',
    appId: '1:573518666505:android:b5f14566abed9ed76bd1d8',
    messagingSenderId: '573518666505',
    projectId: 'tutorial-a8d55',
    storageBucket: 'tutorial-a8d55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABUkTwgPOe53PNOH6GDsMJynJa32qBK0w',
    appId: '1:573518666505:ios:d27c9ec21ef163c26bd1d8',
    messagingSenderId: '573518666505',
    projectId: 'tutorial-a8d55',
    storageBucket: 'tutorial-a8d55.appspot.com',
    iosBundleId: 'com.example.tutorialFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABUkTwgPOe53PNOH6GDsMJynJa32qBK0w',
    appId: '1:573518666505:ios:247e904955eb5d0d6bd1d8',
    messagingSenderId: '573518666505',
    projectId: 'tutorial-a8d55',
    storageBucket: 'tutorial-a8d55.appspot.com',
    iosBundleId: 'com.example.tutorialFlutterApp.RunnerTests',
  );
}
